# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'whale-ios-tassos' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for whale-ios-tassos
  pod 'Kingfisher'
  pod 'Gloss'
  pod 'KeychainSwift'
  pod 'Alamofire'
  pod 'KeychainAccess'
  pod 'SwiftyOnboard'

end
